import React, { useState } from 'react';
import { BilingualHoverCard } from './BilingualHoverCard';
import { useLanguage } from '../context/LanguageContext';
import { ShieldAlert, Award, ArrowUpRight, Scale, Share2, Check } from 'lucide-react';

interface DebateArenaProps {
  debateData: any;
  isPlainTalk?: boolean;
}

export const DebateArena: React.FC<DebateArenaProps> = ({ debateData, isPlainTalk = false }) => {
  const { t } = useLanguage();
  const [copied, setCopied] = useState(false);

  if (!debateData) return null;

  const bull = debateData.bull_argument || {};
  const bear = debateData.bear_argument || {};
  const cio = debateData.cio_verdict || {};

  const handleCopyVerdict = () => {
    const bullPoints = (bull.key_points || ["High Free Cash Flow conversion", "Dominant market leadership position"])
      .map((p: string) => `• ${p}`)
      .join('\n');
    const bearPoints = (bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"])
      .map((p: string) => `• ${p}`)
      .join('\n');

    const snippet = `[Prism Loop Multi-Agent Debate & CIO Verdict]\n` +
      `Verdict: ${cio.verdict || "ACCUMULATE ON PULLBACKS"} (Risk/Reward: ${cio.risk_reward_ratio || 2.4}:1)\n\n` +
      `Bull Case Advocate:\n${bullPoints}\n` +
      (bull.upside_catalyst ? `Key Catalyst: ${bull.upside_catalyst}\n\n` : '\n') +
      `Bear Case Prosecutor:\n${bearPoints}\n` +
      (bear.downside_risk ? `Key Downside Risk: ${bear.downside_risk}\n\n` : '\n') +
      `CIO Summary: ${cio.judge_summary || "Ground-truth audit confirms solid FCF conversion and wide economic moat."}\n` +
      `Recommended Buy Bracket: ${cio.recommended_buy_bracket || "Ideal Buy Zone"}\n` +
      `Position Sizing: ${cio.position_sizing_advice || "3.5% Max Portfolio Weight"}\n\n` +
      `Analysis generated by Prism Loop — Multi-Spectrum Equity Intelligence`;

    navigator.clipboard.writeText(snippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className={`prism-card p-5 mb-6 transition-all ${
      isPlainTalk ? 'border-warning' : ''
    }`}>
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-border-subtle pb-3 mb-5">
        <div className="flex items-center gap-3">
          <div className="p-2.5 prism-badge-warning rounded-xl">
            <Scale className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-content-primary flex items-center gap-2">
              <span>{t.debateTitle}</span>
              {isPlainTalk && (
                <span className="prism-badge-warning text-[10px]">
                  PlainTalk Mode
                </span>
              )}
            </h3>
            <p className="text-xs text-content-muted">
              {t.debateSubtitle}
            </p>
          </div>
        </div>

        {/* 1-Click Copy Debate Verdict for Reddit / X */}
        <button
          onClick={handleCopyVerdict}
          className="px-3.5 py-1.5 bg-surface hover:bg-surface-subtle border border-border-subtle hover:border-brand text-content-primary rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all shadow-sm cursor-pointer"
          title="Copy formatted markdown debate verdict for Reddit, X, and Discord"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-positive" />
              <span className="text-positive font-bold">Copied to Clipboard!</span>
            </>
          ) : (
            <>
              <Share2 className="w-3.5 h-3.5 text-brand" />
              <span>Copy Verdict for Reddit/X</span>
            </>
          )}
        </button>
      </div>

      {/* Arena Debate Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        {/* Bull Case Card */}
        <div className="prism-surface-subtle p-4 border-l-4 border-l-positive flex flex-col justify-between shadow-sm">
          <div>
            <div className="flex items-center justify-between text-xs font-bold text-positive mb-2 pb-2 border-b border-border-subtle">
              <span className="flex items-center gap-1.5">
                <Award className="w-4 h-4" />
                <span>
                  <BilingualHoverCard termKey="BullAgent" isPlainTalk={isPlainTalk}>
                    {t.bullCase}
                  </BilingualHoverCard>
                </span>
              </span>
            </div>
            <ul className="space-y-2 text-xs text-content-secondary mb-4">
              {(bull.key_points || ["High Free Cash Flow conversion", "Dominant market leadership position"]).map((pt: string, idx: number) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-positive font-bold">•</span>
                  <span>{pt}</span>
                </li>
              ))}
            </ul>
          </div>
          {bull.upside_catalyst && (
            <div className="prism-badge-positive p-2.5 rounded-lg text-xs">
              <span className="font-bold block mb-0.5 flex items-center gap-1">
                <ArrowUpRight className="w-3.5 h-3.5" /> {t.keyUpsideCatalyst}:
              </span>
              <span className="font-medium text-content-primary">{bull.upside_catalyst}</span>
            </div>
          )}
        </div>

        {/* Bear Case Card */}
        <div className="prism-surface-subtle p-4 border-l-4 border-l-negative flex flex-col justify-between shadow-sm">
          <div>
            <div className="flex items-center justify-between text-xs font-bold text-negative mb-2 pb-2 border-b border-border-subtle">
              <span className="flex items-center gap-1.5">
                <ShieldAlert className="w-4 h-4" />
                <span>
                  <BilingualHoverCard termKey="BearAgent" isPlainTalk={isPlainTalk}>
                    {t.bearCase}
                  </BilingualHoverCard>
                </span>
              </span>
            </div>
            <ul className="space-y-2 text-xs text-content-secondary mb-4">
              {(bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"]).map((pt: string, idx: number) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-negative font-bold">•</span>
                  <span>{pt}</span>
                </li>
              ))}
            </ul>
          </div>
          {bear.downside_risk && (
            <div className="prism-badge-negative p-2.5 rounded-lg text-xs">
              <span className="font-bold block mb-0.5 flex items-center gap-1">
                <ShieldAlert className="w-3.5 h-3.5" /> {t.keyDownsideRisk}:
              </span>
              <span className="font-medium text-content-primary">{bear.downside_risk}</span>
            </div>
          )}
        </div>
      </div>

      {/* CIO Final Verdict Banner */}
      <div className="prism-surface-subtle p-4 border-l-4 border-l-brand shadow-sm">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <span className="prism-badge-brand text-xs">
              <BilingualHoverCard termKey="CIOVerdict" isPlainTalk={isPlainTalk}>
                {t.cioVerdict}
              </BilingualHoverCard>
            </span>
            <span className="text-xs font-extrabold text-positive">{cio.verdict || "ACCUMULATE ON PULLBACKS"}</span>
          </div>
          <span className="text-xs font-bold text-content-secondary">
            <BilingualHoverCard termKey="RiskReward" isPlainTalk={isPlainTalk}>
              {t.riskReward}
            </BilingualHoverCard>: <span className="text-brand font-mono">{cio.risk_reward_ratio || 2.4}:1</span>
          </span>
        </div>

        <p className="text-xs text-content-primary leading-relaxed font-medium mb-3">
          {cio.judge_summary || "Ground-truth audit confirms solid FCF conversion and wide economic moat, supporting disciplined DCA allocation."}
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs border-t border-border-subtle pt-2.5">
          <div className="text-content-secondary">
            <span className="text-content-muted">
              <BilingualHoverCard termKey="IdealBuyZone" isPlainTalk={isPlainTalk}>
                {t.recommendedBuyBracket}
              </BilingualHoverCard>: 
            </span>
            <span className="font-bold text-warning"> {cio.recommended_buy_bracket || "Ideal Buy Zone"}</span>
          </div>
          <div className="text-content-secondary">
            <span className="text-content-muted">
              <BilingualHoverCard termKey="PositionSizing" isPlainTalk={isPlainTalk}>
                {t.positionSizing}
              </BilingualHoverCard>: 
            </span>
            <span className="font-semibold text-positive"> {cio.position_sizing_advice || "3.5% Portfolio Max Weight"}</span>
          </div>
        </div>
      </div>
    </div>
  );
};
