/**
 * Investment Memo Export Utility
 * Formats full single-stock analysis, multi-agent debate, SEC text mining,
 * and quantitative backtest metrics into styled Markdown (.md) and Printable HTML/PDF.
 */

export interface ExportMemoData {
  stock: any;
  macro: any;
  pricing: any;
  debate: any;
  fundamentals: any;
  secMining?: any;
  backtest?: any;
  language: string;
}

export const generateMarkdownMemo = (data: ExportMemoData): string => {
  const { stock, macro, pricing, debate, fundamentals, secMining, backtest, language = 'en' } = data;
  const isZh = language === 'zh';
  const isHybrid = language === 'hybrid';
  const dateStr = new Date().toISOString().split('T')[0];

  const bull = debate?.bull_argument || {};
  const bear = debate?.bear_argument || {};
  const cio = debate?.cio_verdict || {};

  const getSentimentTone = (sentiment: any, fallback: string): string => {
    if (!sentiment) return fallback;
    if (typeof sentiment === 'string') return sentiment;
    if (typeof sentiment === 'object') {
      return sentiment.tone || (typeof sentiment.score === 'number' ? `Score ${sentiment.score}` : fallback);
    }
    return String(sentiment);
  };

  const macroStage = macro?.cycle_stage || macro?.stage || (isZh ? '晚周期过渡阶段' : 'Late-Cycle Transition');
  const fedTone = getSentimentTone(macro?.fed_sentiment, isZh ? '偏鹰派政策立场' : 'Hawkish Policy Rate Stance');
  const bocTone = getSentimentTone(macro?.boc_sentiment, isZh ? '中性 / 依数据而定' : 'Neutral / Data Dependent');

  const titleHeader = isZh
    ? `# ${stock.company_name} ($${stock.symbol}) 机构级投研备忘录`
    : isHybrid
    ? `# ${stock.company_name} ($${stock.symbol}) 机构级投研备忘录 (Institutional Investment Memo)`
    : `# ${stock.company_name} ($${stock.symbol}) Institutional Investment Memo`;

  const subHeader = isZh
    ? `*由 Prism Loop 多维光谱智能投研工作站生成 • ${dateStr}*`
    : isHybrid
    ? `*Generated by Prism Loop Workstation (多维光谱智能投研工作站) • ${dateStr}*`
    : `*Generated by Prism Loop Workstation • Multi-Spectrum Equity Intelligence on ${dateStr}*`;

  return `${titleHeader}
${subHeader}

---

## ${isZh ? '执行摘要与估值矩阵' : isHybrid ? '执行摘要与估值矩阵 (Executive Summary & Valuation Matrix)' : 'Executive Summary & Valuation Matrix'}

- **${isZh ? '公司名称' : 'Company Name'}**: ${stock.company_name}
- **${isZh ? '股票代码' : 'Ticker Symbol'}**: \`$${stock.symbol}\` (${stock.market || 'US'})
- **${isZh ? '当前市价' : 'Current Market Price'}**: $${stock.current_price} ${pricing?.currency || 'USD'}
- **${isZh ? '理想买入区间' : 'Ideal Buy Bracket'}**: $${pricing?.ideal_buy_range_min || 0} – $${pricing?.ideal_buy_range_max || 0} ${pricing?.currency || 'USD'}
- **${isZh ? 'DCF 内在公允价值' : 'DCF Intrinsic Fair Value'}**: $${pricing?.dcf_fair_value || 0} ${pricing?.currency || 'USD'}
- **${isZh ? '估值状态' : 'Valuation Assessment'}**: ${pricing?.valuation_status || 'FAIRLY VALUED'}
- **${isZh ? '操作状态' : 'Action Status'}**: ${pricing?.action_status || 'MONITOR'}
- **${isZh ? '护城河评级' : 'Moat Rating'}**: ${fundamentals?.moat_rating || 'Wide Moat'}
- **${isZh ? '宏观周期匹配' : 'Macro Cycle Alignment'}**: ${macroStage} (Fed: **${fedTone}**)

---

## ${isZh ? '1. 北美宏观周期扫描与政策立场' : isHybrid ? '1. 北美宏观周期扫描与政策立场 (Macro Cycle Scanner Context)' : '1. North American Macro Cycle Scanner Context'}

- **${isZh ? '当前宏观周期阶段' : 'Current Cycle Stage'}**: ${macroStage}
- **${isZh ? '顺周期板块匹配' : 'Overweight Sector Match'}**: ${macro?.recommended_overweights?.includes(stock.sector) || macro?.overweight_sectors?.includes(stock.sector) ? (isZh ? '命中 (机构顺周期超配行业)' : 'MATCHED (Overweight Sector)') : (isZh ? '标准行业基准配置' : 'Standard Allocation')}
- **${isZh ? '美联储 NLP 情绪' : 'Federal Reserve NLP Sentiment'}**: ${fedTone}
- **${isZh ? '加拿大央行 NLP 情绪' : 'Bank of Canada NLP Sentiment'}**: ${bocTone}

---

## ${isZh ? '2. 多智能体投资辩论竞技场与 CIO 裁决' : isHybrid ? '2. 多智能体投资辩论竞技场与 CIO 裁决 (Multi-Agent Investment Arena & CIO Verdict)' : '2. Multi-Agent Institutional Investment Arena & CIO Verdict'}

### ${isZh ? '看多先锋 (Bull Case Advocate)' : 'Bull Case Advocate'}
- **${isZh ? '智能体角色' : 'Agent Role'}**: ${bull.agent || "Bullish Analyst"}
- **${isZh ? '核心投资催化剂' : 'Key Investment Catalysts'}**:
${(bull.key_points || ["High Free Cash Flow conversion", "Dominant market leadership position"]).map((pt: string) => `  - ${pt}`).join('\n')}
- **${isZh ? '首要上涨催化剂' : 'Key Upside Catalyst'}**: ${bull.upside_catalyst || 'Sustained revenue growth expansion'}

### ${isZh ? '看空检察官 (Bear Case Prosecutor)' : 'Bear Case Prosecutor'}
- **${isZh ? '智能体角色' : 'Agent Role'}**: ${bear.agent || "Bearish Auditor"}
- **${isZh ? '核心下行风险' : 'Key Downside Risks'}**:
${(bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"]).map((pt: string) => `  - ${pt}`).join('\n')}
- **${isZh ? '首要下行风险' : 'Key Downside Risk'}**: ${bear.downside_risk || 'Margin compression in high rate environment'}

### ${isZh ? '首席投资官 (CIO) 最终裁决' : 'Chief Investment Officer (CIO) Verdict'}
- **${isZh ? '投资评级' : 'Verdict'}**: **${cio.verdict || "ACCUMULATE ON PULLBACKS"}**
- **${isZh ? '风险/回报比' : 'Risk / Reward Ratio'}**: **${typeof cio.risk_reward_ratio === 'number' ? cio.risk_reward_ratio.toFixed(1) : (cio.risk_reward_ratio ?? '2.1')}:1**
- **${isZh ? '建议建仓区间' : 'Recommended Buy Bracket'}**: **${cio.recommended_buy_bracket || "Ideal Buy Zone"}**
- **${isZh ? '建议仓位上限' : 'Position Sizing Advice'}**: **${cio.position_sizing_advice || "3.5% Portfolio Max Weight"}**
- **${isZh ? 'CIO 决策依据' : 'CIO Decision Rationale'}**: ${cio.judge_summary || "Ground-truth audit confirms solid FCF conversion and wide economic moat."}

---

## ${isZh ? '3. SEC 10-K 与 SEDAR+ 年报文本挖掘审计' : isHybrid ? '3. SEC 10-K 与 SEDAR+ 年报挖掘 (SEC 10-K & SEDAR+ Text Mining)' : '3. SEC 10-K & SEDAR+ Text Mining Pipeline'}

${secMining ? `
- **${isZh ? '年报披露源' : 'Filing Repository'}**: ${secMining.filing_repository || 'SEC EDGAR / SEDAR+'}
- **${isZh ? '历史解析年份' : 'Historical Years Parsed'}**: ${secMining.historical_years_parsed || 5} ${isZh ? '年' : 'Years'}
- **${isZh ? '审计摘要' : 'Audit Summary'}**: ${secMining.summary_note || 'Levenshtein diffing completed across annual filings.'}

### ${isZh ? '最新年度文本挖掘动态' : 'Recent Year Text Mining Timeline'} (${secMining.text_mining_timeline?.[0]?.year || '2025'})
- **${isZh ? '年报文本相似度' : 'Filing Similarity Score'}**: ${Math.round((secMining.text_mining_timeline?.[0]?.similarity_score || 0.85) * 100)}%
- **${isZh ? '风险异动评级' : 'Risk Severity Rating'}**: ${secMining.text_mining_timeline?.[0]?.severity || 'MEDIUM'}
- **${isZh ? '管理层新补风险条款' : 'Inserted Risk Disclaimer'}**: ${secMining.text_mining_timeline?.[0]?.added_disclaimer || 'Standard macro uncertainty clauses.'}
- **${isZh ? '管理层删减/降级条款' : 'Removed / Reclassified Disclaimer'}**: ${secMining.text_mining_timeline?.[0]?.removed_disclaimer || 'Legacy supply chain disclaimers.'}
` : `*${isZh ? '未关联 SEC 年报文本挖掘数据。' : 'SEC text mining audit data not attached.'}*`}

---

## ${isZh ? '4. 5年历史量化回测表现 (2021 – 2025)' : isHybrid ? '4. 5年历史量化回测 (5-Year Historical Quantitative Backtest)' : '4. 5-Year Historical Quantitative Backtest (2021 – 2025)'}

${backtest ? `
- **${isZh ? '对比基准' : 'Benchmark'}**: ${backtest.benchmark || 'S&P 500 (SPY)'}
- **5-Year CAGR**: **+${backtest.cagr_pct}%** (vs Benchmark: +${backtest.benchmark_cagr_pct}%)
- **Sharpe Ratio**: **${backtest.sharpe_ratio}**
- **Max Drawdown**: **-${backtest.max_drawdown_pct}%**
- **Win Rate vs Benchmark**: **${backtest.win_rate_pct}%**
- **${isZh ? '表现总结' : 'Performance Summary'}**: ${backtest.summary_note || 'Outperformed benchmark across historical macro cycle shifts.'}
` : `*${isZh ? '未关联历史量化回测指标。' : 'Quantitative backtest metrics not attached.'}*`}

---

*Report exported via **Prism Loop** Autonomous Equity Intelligence Workstation.*  
*Open-Source Research & Live Telemetry: [https://github.com/edzhangcan/ai-investment](https://github.com/edzhangcan/ai-investment)*  
*Data is derived strictly from empirical sources (FRED, Bank of Canada, SEC EDGAR, SEDAR+, Yahoo Finance).*
`;
};

export const downloadMarkdownMemo = (data: ExportMemoData): void => {
  const mdContent = generateMarkdownMemo(data);
  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const fileName = `${data.stock.symbol}_PrismLoop_Investment_Memo_${new Date().toISOString().split('T')[0]}.md`;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const printInstitutionalMemo = (data: ExportMemoData): void => {
  const { stock, macro, pricing, debate, fundamentals, secMining, backtest, language = 'en' } = data;
  const isZh = language === 'zh';
  const isHybrid = language === 'hybrid';

  const bull = debate?.bull_argument || {};
  const bear = debate?.bear_argument || {};
  const cio = debate?.cio_verdict || {};

  const getSentimentTone = (sentiment: any, fallback: string): string => {
    if (!sentiment) return fallback;
    if (typeof sentiment === 'string') return sentiment;
    if (typeof sentiment === 'object') {
      return sentiment.tone || (typeof sentiment.score === 'number' ? `Score ${sentiment.score}` : fallback);
    }
    return String(sentiment);
  };

  const macroStage = macro?.cycle_stage || macro?.stage || (isZh ? '晚周期过渡阶段' : 'Late-Cycle Transition');
  const fedTone = getSentimentTone(macro?.fed_sentiment, isZh ? '偏鹰派政策立场' : 'Hawkish Policy Rate Stance');
  const bocTone = getSentimentTone(macro?.boc_sentiment, isZh ? '中性 / 依数据而定' : 'Neutral / Data Dependent');
  const isOverweightMatch = macro?.recommended_overweights?.includes(stock.sector) || macro?.overweight_sectors?.includes(stock.sector);
  const currentDate = new Date().toISOString().split('T')[0];

  const htmlContent = `<!DOCTYPE html>
<html lang="${isZh ? 'zh-CN' : 'en'}">
<head>
  <meta charset="utf-8">
  <title>${stock.company_name} ($${stock.symbol}) - ${isZh ? '机构级投研备忘录' : 'Institutional Investment Memo'}</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 12mm 15mm 12mm 15mm;
    }
    * {
      box-sizing: border-box;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 0;
      font-size: 11px;
      line-height: 1.45;
      position: relative;
    }
    .watermark-overlay {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-32deg);
      font-size: 38px;
      font-weight: 900;
      color: rgba(15, 23, 42, 0.035);
      text-transform: uppercase;
      letter-spacing: 0.18em;
      pointer-events: none;
      white-space: nowrap;
      z-index: 0;
      user-select: none;
    }
    .memo-content {
      position: relative;
      z-index: 1;
    }
    .header-bar {
      border-bottom: 2px solid #0f172a;
      padding-bottom: 10px;
      margin-bottom: 14px;
    }
    .brand-title {
      font-size: 10px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: #0284c7;
      margin-bottom: 2px;
      display: flex;
      align-items: center;
      gap: 6px;
    }
    .brand-logo-mark {
      width: 14px;
      height: 14px;
      display: inline-block;
      vertical-align: middle;
    }
    .memo-title {
      font-size: 22px;
      font-weight: 900;
      color: #0f172a;
      margin: 2px 0 4px 0;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .ticker-badge {
      background: #e0f2fe;
      color: #0369a1;
      border: 1px solid #7dd3fc;
      padding: 2px 8px;
      border-radius: 6px;
      font-size: 13px;
      font-family: monospace;
      font-weight: 800;
    }
    .confidential-tag {
      font-size: 9.5px;
      font-weight: 700;
      color: #92400e;
      background: #fef3c7;
      border: 1px solid #fcd34d;
      padding: 2px 8px;
      border-radius: 4px;
      display: inline-block;
    }
    .section-title {
      font-size: 11px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-top: 12px;
      margin-bottom: 6px;
      padding-bottom: 3px;
      border-bottom: 1px solid #e2e8f0;
      color: #0f172a;
    }
    .grid-4 {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      margin-bottom: 10px;
    }
    .grid-2 {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      margin-bottom: 10px;
    }
    .card {
      background: #f8fafc;
      border: 1px solid #cbd5e1;
      border-radius: 6px;
      padding: 8px 10px;
    }
    .card-label {
      font-size: 9px;
      font-weight: 700;
      text-transform: uppercase;
      color: #64748b;
      margin-bottom: 2px;
    }
    .card-value {
      font-size: 14px;
      font-weight: 900;
      color: #0f172a;
    }
    .text-positive { color: #047857; }
    .text-warning { color: #b45309; }
    .text-brand { color: #0284c7; }
    .text-negative { color: #be123c; }
    .bull-card {
      background: #f0fdf4;
      border-left: 4px solid #10b981;
      border-top: 1px solid #bbf7d0;
      border-right: 1px solid #bbf7d0;
      border-bottom: 1px solid #bbf7d0;
      border-radius: 6px;
      padding: 10px;
    }
    .bear-card {
      background: #fff1f2;
      border-left: 4px solid #f43f5e;
      border-top: 1px solid #fecdd3;
      border-right: 1px solid #fecdd3;
      border-bottom: 1px solid #fecdd3;
      border-radius: 6px;
      padding: 10px;
    }
    .cio-card {
      background: #f8fafc;
      border: 1px solid #94a3b8;
      border-radius: 6px;
      padding: 10px;
      margin-top: 6px;
    }
    ul {
      margin: 4px 0 0 0;
      padding-left: 16px;
    }
    li {
      margin-bottom: 2px;
    }
    .footer {
      border-top: 1px solid #cbd5e1;
      padding-top: 8px;
      margin-top: 16px;
      font-size: 8.5px;
      color: #64748b;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .footer-auth {
      font-weight: 700;
      color: #0284c7;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="watermark-overlay">PRISM LOOP • INSTITUTIONAL RESEARCH WORKSTATION</div>

  <div class="memo-content">
    <div class="header-bar">
      <div style="display: flex; justify-content: space-between; align-items: flex-start;">
        <div>
          <div class="brand-title">
            <svg class="brand-logo-mark" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
              <polygon points="24,4 44,40 4,40" stroke="#0284c7" stroke-width="4" stroke-linejoin="round" fill="none" />
              <line x1="24" y1="4" x2="38" y2="40" stroke="#10b981" stroke-width="2.5" stroke-linecap="round" />
              <line x1="24" y1="4" x2="16" y2="40" stroke="#0ea5e9" stroke-width="2.5" stroke-linecap="round" />
              <line x1="24" y1="4" x2="28" y2="40" stroke="#8b5cf6" stroke-width="2.5" stroke-linecap="round" />
            </svg>
            <span>PRISM LOOP • MULTI-SPECTRUM EQUITY INTELLIGENCE</span>
          </div>
          <div class="memo-title">
            <span>${stock.company_name} <span class="ticker-badge">$${stock.symbol} (${stock.market || 'US'})</span></span>
          </div>
          <div style="font-size: 10px; color: #475569;">
            ${isZh ? '行业板块' : 'Sector'}: <strong>${stock.sector || 'Equities'}</strong> • 
            ${isZh ? '结算货币' : 'Currency'}: <strong>${pricing?.currency || 'USD'}</strong> • 
            ${isZh ? '估值模型' : 'Valuation'}: <strong>10-Yr FCF Discounting + Multi-Tiered MoS</strong>
          </div>
        </div>
        <div style="text-align: right;">
          <div class="confidential-tag">CONFIDENTIAL • INSTITUTIONAL GRADE</div>
          <div style="font-size: 10px; font-weight: 700; color: #475569; margin-top: 4px;">Date: ${currentDate}</div>
        </div>
      </div>
    </div>

    <div class="section-title">${isZh ? '执行摘要与安全边际矩阵' : isHybrid ? '执行摘要与安全边际矩阵 (Valuation & MoS Matrix)' : 'Executive Valuation & Margin of Safety Matrix'}</div>
    <div class="grid-4">
      <div class="card">
        <div class="card-label">${isZh ? '当前市场价格' : 'Current Market Price'}</div>
        <div class="card-value text-positive">$${stock.current_price} <span style="font-size: 9px; font-weight: normal; color: #64748b;">${pricing?.currency || 'USD'}</span></div>
      </div>
      <div class="card">
        <div class="card-label">${isZh ? '理想买入区间' : 'Ideal Buy Bracket'}</div>
        <div class="card-value text-warning">$${pricing?.ideal_buy_range_min || 0} – $${pricing?.ideal_buy_range_max || 0}</div>
      </div>
      <div class="card">
        <div class="card-label">${isZh ? 'DCF 内在公允价值' : 'DCF Intrinsic Fair Value'}</div>
        <div class="card-value text-brand">$${pricing?.dcf_fair_value || 0}</div>
      </div>
      <div class="card">
        <div class="card-label">${isZh ? '护城河评级' : 'Economic Moat Rating'}</div>
        <div class="card-value">${fundamentals?.moat_rating || 'Wide Moat'}</div>
      </div>
    </div>

    <div class="section-title">1. ${isZh ? '北美宏观周期环境与政策立场' : isHybrid ? '北美宏观周期环境 (Macro Cycle Scanner Context)' : 'North American Macro Cycle Context'}</div>
    <div class="card">
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 6px;">
        <div><span class="card-label">${isZh ? '宏观周期阶段' : 'Macro Cycle Stage'}</span><div style="font-weight: 700; color: #b45309;">${macroStage}</div></div>
        <div><span class="card-label">${isZh ? '美联储 NLP 态度' : 'Federal Reserve NLP Stance'}</span><div style="font-weight: 700; color: #0284c7;">${fedTone}</div></div>
        <div><span class="card-label">${isZh ? '加拿大央行 NLP 态度' : 'Bank of Canada NLP Stance'}</span><div style="font-weight: 700; color: #334155;">${bocTone}</div></div>
      </div>
      <div style="font-size: 9.5px; border-top: 1px solid #e2e8f0; padding-top: 4px; color: #475569;">
        ${isZh ? '行业顺周期状态' : 'Sector Overweight Status'}: <strong>${isOverweightMatch ? (isZh ? '命中 (机构顺周期超配行业)' : 'MATCHED (Institutional Sector Overweight)') : (isZh ? '标准行业基准配置' : 'Standard Sector Allocation')}</strong>
      </div>
    </div>

    <div class="section-title">2. ${isZh ? '多智能体投资竞技场与 CIO 裁决' : isHybrid ? '多智能体投资竞技场 (Multi-Agent Debate Arena & CIO Verdict)' : 'Multi-Agent Investment Arena & CIO Verdict'}</div>
    <div class="grid-2">
      <div class="bull-card">
        <div style="font-weight: 800; color: #047857; margin-bottom: 4px;">${isZh ? '看多先锋' : 'Bull Case Advocate'} (${bull.agent || "Bullish Analyst"})</div>
        <ul>
          ${(bull.key_points || ["High Free Cash Flow conversion rate", "Dominant market leadership & pricing power"]).map((pt: string) => `<li>${pt}</li>`).join('')}
        </ul>
        ${bull.upside_catalyst ? `<div style="font-size: 9.5px; font-weight: 700; color: #047857; margin-top: 6px; padding-top: 4px; border-top: 1px solid #bbf7d0;">${isZh ? '主要催化剂' : 'Upside Catalyst'}: ${bull.upside_catalyst}</div>` : ''}
      </div>

      <div class="bear-card">
        <div style="font-weight: 800; color: #be123c; margin-bottom: 4px;">${isZh ? '看空检察官' : 'Bear Case Prosecutor'} (${bear.agent || "Bearish Auditor"})</div>
        <ul>
          ${(bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"]).map((pt: string) => `<li>${pt}</li>`).join('')}
        </ul>
        ${bear.downside_risk ? `<div style="font-size: 9.5px; font-weight: 700; color: #be123c; margin-top: 6px; padding-top: 4px; border-top: 1px solid #fecdd3;">${isZh ? '主要下行风险' : 'Downside Risk'}: ${bear.downside_risk}</div>` : ''}
      </div>
    </div>

    <div class="cio-card">
      <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; margin-bottom: 6px;">
        <div style="font-weight: 900; font-size: 11.5px; color: #b45309;">${isZh ? '首席投资官 (CIO) 最终裁决' : 'Chief Investment Officer (CIO) Verdict'}: ${cio.verdict || 'ACCUMULATE ON PULLBACKS'}</div>
        <div style="font-size: 9.5px; font-family: monospace; font-weight: 700;">
          <span style="color: #0284c7;">${isZh ? '风险/回报' : 'Risk/Reward'}: ${typeof cio.risk_reward_ratio === 'number' ? cio.risk_reward_ratio.toFixed(1) : (cio.risk_reward_ratio ?? '2.1')}:1</span> • 
          <span style="color: #047857;">${isZh ? '建议仓位' : 'Max Weight'}: ${cio.position_sizing_advice || '3.5%'}</span>
        </div>
      </div>
      <div style="font-size: 9.5px; color: #334155; line-height: 1.45;">${cio.judge_summary || 'Ground-truth audit confirms solid FCF conversion, wide economic moat, and resilient pricing power.'}</div>
    </div>

    ${secMining ? `
    <div class="section-title">3. ${isZh ? 'SEC 10-K 与 SEDAR+ 年报文本挖掘审计 (5年差分)' : isHybrid ? 'SEC 10-K 与 SEDAR+ 年报挖掘 (5-Year Diff Audit)' : 'SEC 10-K & SEDAR+ Text Mining Audit (5-Year Diff)'}</div>
    <div class="card">
      <div style="font-size: 9.5px; font-weight: 700; margin-bottom: 2px;">${isZh ? '年报披露源' : 'Repository'}: ${secMining.filing_repository || 'SEC EDGAR / SEDAR+'} (${secMining.historical_years_parsed || 5} ${isZh ? '年解析' : 'Years Parsed'})</div>
      <div style="font-size: 9.5px; color: #475569; margin-bottom: 4px;">${isZh ? '审计记录' : 'Audit Note'}: ${secMining.summary_note || 'Levenshtein diffing completed across annual filings.'}</div>
      ${secMining.text_mining_timeline?.[0] ? `
      <div style="font-size: 9px; border-top: 1px solid #e2e8f0; padding-top: 4px;">
        <div style="color: #be123c;"><strong>+ ${isZh ? '新增风险免责声明' : 'Added Risk Disclaimer'} (${secMining.text_mining_timeline[0].year}):</strong> ${secMining.text_mining_timeline[0].added_disclaimer}</div>
        <div style="color: #64748b; margin-top: 2px;"><strong>- ${isZh ? '删减/降级条款' : 'Removed Clause'}:</strong> ${secMining.text_mining_timeline[0].removed_disclaimer}</div>
      </div>
      ` : ''}
    </div>
    ` : ''}

    ${backtest ? `
    <div class="section-title">4. ${isZh ? '5年历史量化风险与回报表现 (2021 – 2025)' : isHybrid ? '5年历史量化回测 (5-Year Quantitative Risk & Return)' : '5-Year Quantitative Risk & Return (2021 – 2025)'}</div>
    <div class="grid-4">
      <div class="card"><div class="card-label">CAGR</div><div class="card-value text-positive">+${backtest.cagr_pct}%</div></div>
      <div class="card"><div class="card-label">Sharpe Ratio</div><div class="card-value text-brand">${backtest.sharpe_ratio}</div></div>
      <div class="card"><div class="card-label">Max Drawdown</div><div class="card-value text-negative">-${backtest.max_drawdown_pct}%</div></div>
      <div class="card"><div class="card-label">Win Rate</div><div class="card-value text-warning">${backtest.win_rate_pct}%</div></div>
    </div>
    ` : ''}

    <div class="footer">
      <div><strong>${isZh ? '数据来源' : 'Sources'}:</strong> Federal Reserve (FRED), Bank of Canada, SEC EDGAR, SEDAR+, Yahoo Finance. Local-First Zero-Hallucination Engine.</div>
      <div><strong>${isZh ? '平台归属' : 'Generated by'}:</strong> <span class="footer-auth">Prism Loop Workstation • github.com/edzhangcan/ai-investment</span></div>
    </div>
  </div>
</body>
</html>`;

  const printFrame = document.createElement('iframe');
  printFrame.style.position = 'fixed';
  printFrame.style.right = '0';
  printFrame.style.bottom = '0';
  printFrame.style.width = '0';
  printFrame.style.height = '0';
  printFrame.style.border = 'none';
  printFrame.style.visibility = 'hidden';
  document.body.appendChild(printFrame);

  const doc = printFrame.contentWindow?.document;
  if (doc) {
    doc.open();
    doc.write(htmlContent);
    doc.close();

    setTimeout(() => {
      printFrame.contentWindow?.focus();
      printFrame.contentWindow?.print();
      setTimeout(() => {
        if (document.body.contains(printFrame)) {
          document.body.removeChild(printFrame);
        }
      }, 1000);
    }, 200);
  }
};

