/**
 * Investment Memo Export Utility
 * Formats full single-stock analysis, multi-agent debate, SEC text mining,
 * and quantitative backtest metrics into styled Markdown (.md) and Printable HTML/PDF.
 */

export interface ExportMemoData {
  stock: any;
  macro: any;
  pricing: any;
  debate: any;
  fundamentals: any;
  secMining?: any;
  backtest?: any;
  language: string;
}

export const generateMarkdownMemo = (data: ExportMemoData): string => {
  const { stock, macro, pricing, debate, fundamentals, secMining, backtest } = data;
  const dateStr = new Date().toISOString().split('T')[0];

  const bull = debate?.bull_argument || {};
  const bear = debate?.bear_argument || {};
  const cio = debate?.cio_verdict || {};

  const getSentimentTone = (sentiment: any, fallback: string): string => {
    if (!sentiment) return fallback;
    if (typeof sentiment === 'string') return sentiment;
    if (typeof sentiment === 'object') {
      return sentiment.tone || (typeof sentiment.score === 'number' ? `Score ${sentiment.score}` : fallback);
    }
    return String(sentiment);
  };

  const macroStage = macro?.cycle_stage || macro?.stage || 'Late-Cycle Transition';
  const fedTone = getSentimentTone(macro?.fed_sentiment, 'Hawkish Policy Rate Stance');
  const bocTone = getSentimentTone(macro?.boc_sentiment, 'Neutral / Data Dependent');

  return `# Institutional Investment Memo: ${stock.company_name} ($${stock.symbol})
*Generated by Prism Loop Workstation • Multi-Spectrum Equity Intelligence on ${dateStr}*

---

## Executive Summary & Market Snapshot

- **Company Name**: ${stock.company_name}
- **Ticker Symbol**: \`$${stock.symbol}\` (${stock.market || 'US'})
- **Current Market Price**: $${stock.current_price} ${pricing?.currency || 'USD'}
- **Ideal Entry Bracket**: $${pricing?.ideal_buy_range_min || 0} – $${pricing?.ideal_buy_range_max || 0} ${pricing?.currency || 'USD'}
- **DCF Intrinsic Fair Value**: $${pricing?.dcf_fair_value || 0} ${pricing?.currency || 'USD'}
- **Valuation Assessment**: ${pricing?.valuation_status || 'FAIRLY VALUED'}
- **Action Status**: ${pricing?.action_status || 'MONITOR'}
- **Moat Rating**: ${fundamentals?.moat_rating || 'Wide Moat'}
- **Macro Cycle Alignment**: Stage **${macroStage}** (Fed: **${fedTone}**)

---

## North American Macro Cycle Scanner Context

- **Current Cycle Stage**: ${macroStage}
- **Overweight Sector Match**: ${macro?.recommended_overweights?.includes(stock.sector) || macro?.overweight_sectors?.includes(stock.sector) ? 'MATCHED (Overweight Sector)' : 'Standard Allocation'}
- **Fed NLP Sentiment**: ${fedTone}
- **BoC NLP Sentiment**: ${bocTone}

---

## Multi-Agent Institutional Investment Arena

### Bull Case Advocate
- **Agent Role**: ${bull.agent || "Bullish Analyst"}
- **Key Investment Catalysts**:
${(bull.key_points || ["High Free Cash Flow conversion", "Dominant market leadership position"]).map((pt: string) => `  - ${pt}`).join('\n')}
- **Key Upside Catalyst**: ${bull.upside_catalyst || 'Sustained revenue growth expansion'}

### Bear Case Prosecutor
- **Agent Role**: ${bear.agent || "Bearish Auditor"}
- **Key Downside Risks**:
${(bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"]).map((pt: string) => `  - ${pt}`).join('\n')}
- **Key Downside Risk**: ${bear.downside_risk || 'Margin compression in high rate environment'}

### Chief Investment Officer (CIO) Verdict
- **Verdict**: **${cio.verdict || "ACCUMULATE ON PULLBACKS"}**
- **Risk / Reward Ratio**: **${typeof cio.risk_reward_ratio === 'number' ? cio.risk_reward_ratio.toFixed(1) : (cio.risk_reward_ratio ?? '2.1')}:1**
- **Recommended Buy Bracket**: **${cio.recommended_buy_bracket || "Ideal Buy Zone"}**
- **Position Sizing Advice**: **${cio.position_sizing_advice || "3.5% Portfolio Max Weight"}**
- **CIO Decision Rationale**: ${cio.judge_summary || "Ground-truth audit confirms solid FCF conversion and wide economic moat."}

---

## SEC 10-K & SEDAR+ Text Mining Pipeline

${secMining ? `
- **Filing Repository**: ${secMining.filing_repository || 'SEC EDGAR / SEDAR+'}
- **Historical Years Parsed**: ${secMining.historical_years_parsed || 5} Years
- **Audit Summary**: ${secMining.summary_note || 'Levenshtein diffing completed across annual filings.'}

### Recent Year Text Mining Timeline (${secMining.text_mining_timeline?.[0]?.year || '2025'})
- **Filing Similarity Score**: ${Math.round((secMining.text_mining_timeline?.[0]?.similarity_score || 0.85) * 100)}%
- **Risk Severity Rating**: ${secMining.text_mining_timeline?.[0]?.severity || 'MEDIUM'}
- **Inserted Risk Disclaimer**: ${secMining.text_mining_timeline?.[0]?.added_disclaimer || 'Standard macro uncertainty clauses.'}
- **Removed / Reclassified Disclaimer**: ${secMining.text_mining_timeline?.[0]?.removed_disclaimer || 'Legacy COVID supply chain disclaimers.'}
` : '*SEC text mining audit data not attached.*'}

---

## 5-Year Historical Quantitative Backtest (2021 – 2025)

${backtest ? `
- **Benchmark**: ${backtest.benchmark || 'S&P 500 (SPY)'}
- **5-Year CAGR**: **+${backtest.cagr_pct}%** (vs Benchmark: +${backtest.benchmark_cagr_pct}%)
- **Sharpe Ratio**: **${backtest.sharpe_ratio}**
- **Max Drawdown**: **-${backtest.max_drawdown_pct}%**
- **Win Rate vs Benchmark**: **${backtest.win_rate_pct}%**
- **Performance Summary**: ${backtest.summary_note || 'Outperformed benchmark across historical macro cycle shifts.'}
` : '*Quantitative backtest metrics not attached.*'}

---
*Report exported via **Prism Loop** Autonomous Equity Intelligence Workstation.*  
*Open-Source Research & Live Telemetry: [https://github.com/edzhangcan/ai-investment](https://github.com/edzhangcan/ai-investment)*  
*Data is derived strictly from empirical sources (FRED, Bank of Canada, SEC EDGAR, SEDAR+, Yahoo Finance).*
`;
};

export const downloadMarkdownMemo = (data: ExportMemoData): void => {
  const mdContent = generateMarkdownMemo(data);
  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const fileName = `${data.stock.symbol}_PrismLoop_Investment_Memo_${new Date().toISOString().split('T')[0]}.md`;
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const printInstitutionalMemo = (data: ExportMemoData): void => {
  const { stock, macro, pricing, debate, fundamentals, secMining, backtest } = data;
  const bull = debate?.bull_argument || {};
  const bear = debate?.bear_argument || {};
  const cio = debate?.cio_verdict || {};

  const getSentimentTone = (sentiment: any, fallback: string): string => {
    if (!sentiment) return fallback;
    if (typeof sentiment === 'string') return sentiment;
    if (typeof sentiment === 'object') {
      return sentiment.tone || (typeof sentiment.score === 'number' ? `Score ${sentiment.score}` : fallback);
    }
    return String(sentiment);
  };

  const macroStage = macro?.cycle_stage || macro?.stage || 'Late-Cycle Transition';
  const fedTone = getSentimentTone(macro?.fed_sentiment, 'Hawkish Policy Rate Stance');
  const bocTone = getSentimentTone(macro?.boc_sentiment, 'Neutral / Data Dependent');
  const isOverweightMatch = macro?.recommended_overweights?.includes(stock.sector) || macro?.overweight_sectors?.includes(stock.sector);
  const currentDate = new Date().toISOString().split('T')[0];

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${stock.company_name} ($${stock.symbol}) - Institutional Investment Memo</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 12mm 15mm 12mm 15mm;
    }
    * {
      box-sizing: border-box;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 0;
      font-size: 11px;
      line-height: 1.45;
    }
    .header-bar {
      border-bottom: 2px solid #0f172a;
      padding-bottom: 10px;
      margin-bottom: 14px;
    }
    .brand-title {
      font-size: 10px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: #0284c7;
      margin-bottom: 2px;
    }
    .memo-title {
      font-size: 22px;
      font-weight: 900;
      color: #0f172a;
      margin: 2px 0 4px 0;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .ticker-badge {
      background: #e0f2fe;
      color: #0369a1;
      border: 1px solid #7dd3fc;
      padding: 2px 8px;
      border-radius: 6px;
      font-size: 13px;
      font-family: monospace;
      font-weight: 800;
    }
    .confidential-tag {
      font-size: 9.5px;
      font-weight: 700;
      color: #92400e;
      background: #fef3c7;
      border: 1px solid #fcd34d;
      padding: 2px 8px;
      border-radius: 4px;
      display: inline-block;
    }
    .section-title {
      font-size: 11px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-top: 12px;
      margin-bottom: 6px;
      padding-bottom: 3px;
      border-bottom: 1px solid #e2e8f0;
      color: #0f172a;
    }
    .grid-4 {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      margin-bottom: 10px;
    }
    .grid-2 {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      margin-bottom: 10px;
    }
    .card {
      background: #f8fafc;
      border: 1px solid #cbd5e1;
      border-radius: 6px;
      padding: 8px 10px;
    }
    .card-label {
      font-size: 9px;
      font-weight: 700;
      text-transform: uppercase;
      color: #64748b;
      margin-bottom: 2px;
    }
    .card-value {
      font-size: 14px;
      font-weight: 900;
      color: #0f172a;
    }
    .text-positive { color: #047857; }
    .text-warning { color: #b45309; }
    .text-brand { color: #0284c7; }
    .text-negative { color: #be123c; }
    .bull-card {
      background: #f0fdf4;
      border-left: 4px solid #10b981;
      border-top: 1px solid #bbf7d0;
      border-right: 1px solid #bbf7d0;
      border-bottom: 1px solid #bbf7d0;
      border-radius: 6px;
      padding: 10px;
    }
    .bear-card {
      background: #fff1f2;
      border-left: 4px solid #f43f5e;
      border-top: 1px solid #fecdd3;
      border-right: 1px solid #fecdd3;
      border-bottom: 1px solid #fecdd3;
      border-radius: 6px;
      padding: 10px;
    }
    .cio-card {
      background: #f8fafc;
      border: 1px solid #94a3b8;
      border-radius: 6px;
      padding: 10px;
      margin-top: 6px;
    }
    ul {
      margin: 4px 0 0 0;
      padding-left: 16px;
    }
    li {
      margin-bottom: 2px;
    }
    .footer {
      border-top: 1px solid #cbd5e1;
      padding-top: 6px;
      margin-top: 14px;
      font-size: 8.5px;
      color: #64748b;
      display: flex;
      justify-content: space-between;
    }
  </style>
</head>
<body>
  <div class="header-bar">
    <div style="display: flex; justify-content: space-between; align-items: flex-start;">
      <div>
        <div class="brand-title">PRISM LOOP • MULTI-SPECTRUM EQUITY INTELLIGENCE</div>
        <div class="memo-title">
          <span>${stock.company_name} <span class="ticker-badge">$${stock.symbol} (${stock.market || 'US'})</span></span>
        </div>
        <div style="font-size: 10px; color: #475569;">Sector: <strong>${stock.sector || 'Equities'}</strong> • Currency: <strong>${pricing?.currency || 'USD'}</strong> • Valuation: <strong>10-Yr FCF Discounting + 3-Stage Terminal Growth</strong></div>
      </div>
      <div style="text-align: right;">
        <div class="confidential-tag">CONFIDENTIAL • INSTITUTIONAL GRADE</div>
        <div style="font-size: 10px; font-weight: 700; color: #475569; margin-top: 4px;">Date: ${currentDate}</div>
      </div>
    </div>
  </div>

  <div class="section-title">Executive Valuation & Margin of Safety Matrix</div>
  <div class="grid-4">
    <div class="card">
      <div class="card-label">Current Market Price</div>
      <div class="card-value text-positive">$${stock.current_price} <span style="font-size: 9px; font-weight: normal; color: #64748b;">${pricing?.currency || 'USD'}</span></div>
    </div>
    <div class="card">
      <div class="card-label">Ideal Buy Bracket</div>
      <div class="card-value text-warning">$${pricing?.ideal_buy_range_min || 0} – $${pricing?.ideal_buy_range_max || 0}</div>
    </div>
    <div class="card">
      <div class="card-label">DCF Intrinsic Fair Value</div>
      <div class="card-value text-brand">$${pricing?.dcf_fair_value || 0}</div>
    </div>
    <div class="card">
      <div class="card-label">Economic Moat Rating</div>
      <div class="card-value">${fundamentals?.moat_rating || 'Wide Moat'}</div>
    </div>
  </div>

  <div class="section-title">1. North American Macro Cycle Context</div>
  <div class="card">
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 6px;">
      <div><span class="card-label">Macro Cycle Stage</span><div style="font-weight: 700; color: #b45309;">${macroStage}</div></div>
      <div><span class="card-label">Federal Reserve NLP Stance</span><div style="font-weight: 700; color: #0284c7;">${fedTone}</div></div>
      <div><span class="card-label">Bank of Canada NLP Stance</span><div style="font-weight: 700; color: #334155;">${bocTone}</div></div>
    </div>
    <div style="font-size: 9.5px; border-top: 1px solid #e2e8f0; padding-top: 4px; color: #475569;">
      Sector Overweight Status: <strong>${isOverweightMatch ? 'MATCHED (Institutional Sector Overweight)' : 'Standard Sector Allocation'}</strong>
    </div>
  </div>

  <div class="section-title">2. Multi-Agent Investment Arena & CIO Verdict</div>
  <div class="grid-2">
    <div class="bull-card">
      <div style="font-weight: 800; color: #047857; margin-bottom: 4px;">Bull Case Advocate (${bull.agent || "Bullish Analyst"})</div>
      <ul>
        ${(bull.key_points || ["High Free Cash Flow conversion rate", "Dominant market leadership & pricing power"]).map((pt: string) => `<li>${pt}</li>`).join('')}
      </ul>
      ${bull.upside_catalyst ? `<div style="font-size: 9.5px; font-weight: 700; color: #047857; margin-top: 6px; padding-top: 4px; border-top: 1px solid #bbf7d0;">Upside Catalyst: ${bull.upside_catalyst}</div>` : ''}
    </div>

    <div class="bear-card">
      <div style="font-weight: 800; color: #be123c; margin-bottom: 4px;">Bear Case Prosecutor (${bear.agent || "Bearish Auditor"})</div>
      <ul>
        ${(bear.key_points || ["Macro headwinds & interest rate sensitivity", "Competitive margin compression risks"]).map((pt: string) => `<li>${pt}</li>`).join('')}
      </ul>
      ${bear.downside_risk ? `<div style="font-size: 9.5px; font-weight: 700; color: #be123c; margin-top: 6px; padding-top: 4px; border-top: 1px solid #fecdd3;">Downside Risk: ${bear.downside_risk}</div>` : ''}
    </div>
  </div>

  <div class="cio-card">
    <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; margin-bottom: 6px;">
      <div style="font-weight: 900; font-size: 11.5px; color: #b45309;">Chief Investment Officer (CIO) Verdict: ${cio.verdict || 'ACCUMULATE ON PULLBACKS'}</div>
      <div style="font-size: 9.5px; font-family: monospace; font-weight: 700;">
        <span style="color: #0284c7;">Risk/Reward: ${typeof cio.risk_reward_ratio === 'number' ? cio.risk_reward_ratio.toFixed(1) : (cio.risk_reward_ratio ?? '2.1')}:1</span> • 
        <span style="color: #047857;">Max Weight: ${cio.position_sizing_advice || '3.5%'}</span>
      </div>
    </div>
    <div style="font-size: 9.5px; color: #334155; line-height: 1.45;">${cio.judge_summary || 'Ground-truth audit confirms solid FCF conversion, wide economic moat, and resilient pricing power.'}</div>
  </div>

  ${secMining ? `
  <div class="section-title">3. SEC 10-K & SEDAR+ Text Mining Audit (5-Year Diff)</div>
  <div class="card">
    <div style="font-size: 9.5px; font-weight: 700; margin-bottom: 2px;">Repository: ${secMining.filing_repository || 'SEC EDGAR / SEDAR+'} (${secMining.historical_years_parsed || 5} Years Parsed)</div>
    <div style="font-size: 9.5px; color: #475569; margin-bottom: 4px;">Audit Note: ${secMining.summary_note || 'Levenshtein diffing completed across annual filings.'}</div>
    ${secMining.text_mining_timeline?.[0] ? `
    <div style="font-size: 9px; border-top: 1px solid #e2e8f0; padding-top: 4px;">
      <div style="color: #be123c;"><strong>+ Added Risk Disclaimer (${secMining.text_mining_timeline[0].year}):</strong> ${secMining.text_mining_timeline[0].added_disclaimer}</div>
      <div style="color: #64748b; margin-top: 2px;"><strong>- Removed Clause:</strong> ${secMining.text_mining_timeline[0].removed_disclaimer}</div>
    </div>
    ` : ''}
  </div>
  ` : ''}

  ${backtest ? `
  <div class="section-title">4. 5-Year Quantitative Risk & Return (2021 – 2025)</div>
  <div class="grid-4">
    <div class="card"><div class="card-label">CAGR</div><div class="card-value text-positive">+${backtest.cagr_pct}%</div></div>
    <div class="card"><div class="card-label">Sharpe Ratio</div><div class="card-value text-brand">${backtest.sharpe_ratio}</div></div>
    <div class="card"><div class="card-label">Max Drawdown</div><div class="card-value text-negative">-${backtest.max_drawdown_pct}%</div></div>
    <div class="card"><div class="card-label">Win Rate</div><div class="card-value text-warning">${backtest.win_rate_pct}%</div></div>
  </div>
  ` : ''}

  <div class="footer">
    <div>Sources: Federal Reserve (FRED), Bank of Canada, SEC EDGAR, SEDAR+, Yahoo Finance. Zero-Hallucination Engine.</div>
    <div>Prism Loop • Multi-Spectrum Equity Intelligence • github.com/edzhangcan/ai-investment</div>
  </div>
</body>
</html>`;

  const printFrame = document.createElement('iframe');
  printFrame.style.position = 'fixed';
  printFrame.style.right = '0';
  printFrame.style.bottom = '0';
  printFrame.style.width = '0';
  printFrame.style.height = '0';
  printFrame.style.border = 'none';
  printFrame.style.visibility = 'hidden';
  document.body.appendChild(printFrame);

  const doc = printFrame.contentWindow?.document;
  if (doc) {
    doc.open();
    doc.write(htmlContent);
    doc.close();

    setTimeout(() => {
      printFrame.contentWindow?.focus();
      printFrame.contentWindow?.print();
      setTimeout(() => {
        if (document.body.contains(printFrame)) {
          document.body.removeChild(printFrame);
        }
      }, 1000);
    }, 200);
  }
};
